src/together/utils/files.py

Due to the changes in https://github.com/togethercomputer/together-python/pull/73, there is now a separate report_dict that is created in `_check_jsonl`. The end of the function checks for multiple keys in that dictionary that are not created by default. This PR fixes the problem by checking for the presence of the key in the dictionary instead

Fix missing keys in report_dict for _check_jsonl

---

pyproject.toml
src/together/resources/finetune.py
src/together/types/finetune.py

This resolves an issue where the WandB API Key was ignored since it was using the wrong field name in the request.

WandB API Param Name fix

---

README.md

I have read the contributing guidelines. Formatting and linting and unit testing checks have been done.
Issue #: None
The Completions endpoint requires the `max_tokens` parameter. This has been added to the example Completions request in `README.md`

Add required parameter max_tokens to completions example

---

src/together/filemanager.py

*Have you read the [Contributing Guidelines](https://github.com/togethercomputer/together/blob/main/CONTRIBUTING.md)?* 
Yes
Intermediate fine-tune checkpoints are missing content-type. We can update future uploads to have this, but backfilling will be difficult. Thus, this change sets the default to zstd for download purposes.

Default FineTune Download File to zstd

---

pyproject.toml
src/together/cli/api/files.py
src/together/error.py
src/together/legacy/files.py
src/together/resources/files.py

Issue # ENG-5104
This PR reverts the old behavior of checking files by default, because the current logic leads to many incorrect files being uploaded, adding friction to user experience (the error messages seen by users do not reveal the source of errors). If users want to skip the check (for example, they are sure the file is correct and checking it takes a long time), they can disable it with `--no-check`

Check uploaded files by default

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py
src/together/types/__init__.py
src/together/types/finetune.py

Issue ENG-4853
Add LoRA training support for finetuning jobs.
Some cli examples:
```bash
together fine-tuning create --training-file "${FILE_ID}" --model "meta-llama/Meta-Llama-3-8B" --wandb-api-key "${WANDB_API_KEY}" --lora --lora-r 8
```
Description of the new parameters:
- `--lora`(bool) -- general flag for enabling LoRA training
- `--lora-r`(int) -- rank for LoRA adapter weights
- `--lora-dropout`(float) -- dropout value for LoRA adapter training
- `--lora-alpha`(int) -- alpha value for LoRA adapter training
- `--lora-trainable-modules`(str) -- LoRA adapters' trainable modules, separated by a comma. To use trainable modules, use `all-linear`

Add LoRA support for FT API

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/together/__init__.py
src/together/abstract/__init__.py
src/together/cli/api/chat.py
src/together/cli/api/completions.py
src/together/cli/api/files.py
src/together/cli/api/finetune.py
src/together/error.py
src/together/legacy/complete.py
src/together/legacy/embeddings.py
src/together/legacy/files.py
src/together/legacy/finetune.py
src/together/legacy/images.py
src/together/legacy/models.py
src/together/resources/chat/completions.py
src/together/resources/completions.py
src/together/resources/embeddings.py
src/together/resources/finetune.py
src/together/resources/images.py
src/together/types/chat_completions.py

- fixes ruff version
- removes ruff from make format due to incompatibility
- fixes null types being decoded with model_dump

bug: exclude null types being decoded with pydantic model_dump()

---

src/together/constants.py

To support smaller validation datasets, the minimum dataset sample size is being reduced to 1 (we still need to make sure the dataset is nonempty). This is a single integer constant change.
```
$ cat ../test.jsonl 
{"text": "hi"}
$ together files check ../test.jsonl
{
"is_check_passed": true,
"message": "Checks passed",
"found": true,
"file_size": 15,
"utf8": true,
"line_type": true,
"text_field": true,
"key_value": true,
"min_samples": true,
"num_samples": 1,
"load_json": true,
"filetype": "jsonl"
}
```

ENG 9390: Files MIN_SAMPLES=1

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py

When users submit a command to fine-tune a model at the moment, the report message prints out the entire response to the fine-tuning request, which contains a lot of technical information and is difficult to understand. This PR replaces that with logging of `FinetuneRequest` instead before the job is submitted and prints the identifier of the job along with its time when the job is accepted by the API.
The difference is easiest to see in screenshots. 
Before:
After:
Fixes ENG-7292

Improve fine-tuning CLI messages with rich

---

pyproject.toml
src/together/cli/api/finetune.py

This PR adds a confirmation message before submitting a fine-tuning job via CLI to communicate the pricing model to the users. Users can skip this message when they submit a job with `-y` or `--confirm` in the set of arguments.
Example output:
```
poetry run together fine-tuning create --training-file $FILE_NAME --model meta-llama/Meta-Llama-3-70B-Instruct --n-epochs 3 --n-checkpoints 3 --no-lora --batch-size 16 --wandb-api-key $WANDB_KEY  --suffix llama3_70b_full
You are about to launch a fine-tuning job. The cost of your job will be determined by the model size, the number of tokens in the training file, the number of tokens in the validation file, the number of epochs, and the number of evaluations. Visit https://www.together.ai/pricing to get a price estimate.
You can add `-y` or …
```

Add a confirmation message before submitting a fine-tuning job

---

README.md
src/together/cli/api/finetune.py
src/together/cli/api/utils.py
src/together/legacy/finetune.py
src/together/resources/finetune.py
src/together/types/__init__.py
src/together/types/finetune.py
src/together/utils/__init__.py
src/together/utils/_log.py

Issue #ENG-10437
I added a logic to request limits for hyperparameters for a requested model. If a user does not specify hyperparameters, togther-python will change it to recommended values.

Change default batch_size for finetuning to max_batch_size for a model

---

pyproject.toml
src/together/cli/api/utils.py

The current implementation of `AutoIntParamType.convert` returns integers only when integers are passed as `value`. However, `value` is defined as a string, so this branch of the code never gets used. As a result, passing `--batch-size 16` (or any other integer) to the command for creating jobs fails with the following error:
```
Error: Invalid value for '--batch-size': Invalid integer value: {value}
```
This PR fixes that error, moving over the code to handle integer inputs correctly from Click

Fix handling of integers in AutoIntParamType

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py
src/together/types/finetune.py

Y
This PR adds support for specifying WandB project name, run name, and base url.

Add WandB base url, project name, run name

---

pyproject.toml
src/together/utils/files.py
tests/unit/test_files_checks.py

This PR adds a check that upload jsonl files do not have columns that aren't relevant. This will also ensure all columns have the same columns.
Part of ENG-14194/fix-ft-jsonl-datasets-error-with-the-extra-column

Add check for unneeded jsonl columns

---

pyproject.toml
src/together/cli/api/finetune.py

This PR removes the warning for the LoRA Rank default value when creating a finetuning job.

Remove the default LoRA rank warning

---

pyproject.toml
src/together/utils/files.py
tests/unit/test_files_checks.py

Issue #ENG-17304
Adds checks for empty messages list in the training data.

Fix empty messages

---

README.md
pyproject.toml
src/together/types/chat_completions.py
tests/unit/test_video_url.py

- Add `VIDEO_URL` type to chat completion message content types
- Implement `ChatCompletionMessageContentVideoURL` model for video URL data
- Add `video_url` field to `ChatCompletionMessageContent` class
- Add unit test to verify video URL message handling
- Update README with multi-modal content documentation including:
- Text-only messages
- Image URL messages
- Video URL messages
- Clear explanation of content type usage
Example usage:
```python
client.chat.completions.create(
messages=[{
"role": "user",
"content": [
{"type": "text", "text": "What's in this video?"},
{"type": "video_url", "video_url": {"url": "https://example.com/video.mp4"}},
],
}],
model="your_model"
)

add video url support to chat.completions

---

README.md
pyproject.toml
src/together/cli/api/finetune.py
src/together/cli/api/utils.py
src/together/legacy/finetune.py
src/together/resources/finetune.py
src/together/types/__init__.py
src/together/types/endpoints.py
src/together/types/finetune.py
src/together/utils/__init__.py
src/together/utils/tools.py

Issue #ENG-18828 , #ENG-18829
Improve fine-tuning checkpoint support with two features:
- Add new command to show all checkpoints for the jobs
- Add new argument to start a job from the checkpoint

Improve fine-tuning checkpoint support

---

src/together/cli/api/finetune.py
src/together/constants.py
src/together/resources/finetune.py
src/together/types/__init__.py
src/together/types/finetune.py
src/together/utils/files.py
tests/unit/test_files_checks.py
tests/unit/test_preference_openai.py

This PR adds support for the Training Method for finetuning, and for Direct-Preference Optimization (DPO).

Add support for the Training Method for finetuning, and for Direct-Preference Optimization (DPO)

---

src/together/cli/api/endpoints.py
src/together/cli/api/models.py
src/together/resources/endpoints.py
src/together/resources/models.py

Adds support for 
```
together models list --type=dedicated
```
Also changes the table to use a simple table, which has similar semantics to docker. This way, users can more easily parse its output by doing, for example, `together models list --type=dedicated | wc -l` or splitting out ID. Also added a `--json` option.
```
together endpoints create --model mistralai/Mixtral-8x7B-Instruct-v0.1 --inactive-timeout 2 --gpu h100 --gpu-count 2
```
Fixes https://linear.app/together-ai/issue/ENG-21594/list-dedicated-models
Fixes https://linear.app/together-ai/issue/ENG-23176/add-autoshutdown-to-public-api-docs-open-api-specs

Support auto shutdown and model list

---

.devcontainer/Dockerfile
.github/workflows/_integration_tests.yml
.github/workflows/_tests.yml
.github/workflows/check_code_quality.yml

This PR fixes GH workflows after the recent deletion of support for Python == 3.9. It also changes the condition for the tests to run on: for any code-related change, tests should run and check changes.

Fix GitHub workflows after removing support for 3.9

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py

Issue # ENG-18831
This PR removes the "require" flag from the `model` field in the fine-tuning create command if the `from_checkpoint` field is set. The latter is enough to derive the model limits and settings required for fine-tuning.

Fix model_name requirements

---

src/together/cli/api/finetune.py

Adds shorctuts for fine-tuning create and download arguments. These have been included in [the docs](https://docs.together.ai/reference/finetune) but were not actually working.

Add shortcuts for arguments specified in the FT docs

---

src/together/filemanager.py

Not much information is currently shared when there is an error during file upload. Adding more info from response object.
I copied the way the APIError was created here:
https://github.com/togethercomputer/together-python/blob/64d0067ec62f9efeb870ed6f2c1c0b59f6424927/src/together/filemanager.py#L259-L262
Fixes #ENG-25010

Add more information from response object to APIError during file upload

---

README.md

Update README to show to use logprobs parameter, and link to https://docs.together.ai/docs/logprobs for more details

Update README to show to use logprobs parameter

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py
src/together/types/finetune.py
tests/unit/test_finetune_resources.py

Issue #
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*

Add a logic to support max_batch_size_dpo.

---

pyproject.toml
src/together/resources/finetune.py

Accept strings for checkpoint type on download

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py
src/together/types/finetune.py
tests/unit/test_finetune_resources.py

this PR adjusts the behavior of train_on_inputs.
if train type is SFT, we include this parameter in the TrainingMethod and default it to auto.
if train type is DPO, we default to None and raise if parameter is supplied.

Migrate train_on_inputs to sft-specific params

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py

Issue #
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*

Fix dpo defaults for cli + turn on the checks removed previously

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/resources/finetune.py
src/together/types/finetune.py

Issue #
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*

Add Hugging Face Hub upload option

---

tests/unit/test_files_checks.py

Issue #
This PR adds tests for conversational weights logic. We check that mixed inputs works as expected (when some messages have weight and other don't) and the case when all the weights are present.
Also we check for the correct error message when user provided weight different from 0 or 1 (we don't allow that), and there are two possible errors, first for the type (it must be integer), second for the value (if integer check is passed then we check if it is 0 or 1).

Add tests for message weights

---

pyproject.toml
src/together/cli/api/finetune.py
src/together/legacy/finetune.py
src/together/resources/finetune.py
src/together/types/finetune.py
tests/unit/test_finetune_resources.py

Issue #
Now we propagate batch_size="max" directly to REST API, where it will be resolved to a numeric value, based on the models' limits.

Removing handling max bs from client, handling in the REST API

---

.gitignore
src/together/constants.py
src/together/filemanager.py
src/together/resources/files.py
src/together/types/files.py
src/together/utils/files.py
tests/unit/test_files_upload_routing.py
tests/unit/test_multipart_upload_manager.py

Add Multipart Upload Support for Large Files
- Implements multipart file upload capability to support fine-tuning with datasets exceeding 5GB, addressing the current single-upload size limitation.
Changes
- MultipartUploadManager: New class implementing 3-phase multipart upload (initiate → upload parts → complete)
- Size-based routing: routing between single upload (≤5GB) and multipart upload (>5GB)
- Concurrent part uploads: simultaneous part uploads with progress tracking via tqdm
- File size validation: 25GB maximum (for now)
-Configuration centralized in constants.py

Implement multipart upload

---

src/together/resources/audio/transcriptions.py
src/together/types/audio_speech.py
tests/integration/resources/test_transcriptions.py

Eng 38484/speaker diarization tests

---

src/together/cli/api/endpoints.py
src/together/resources/endpoints.py

Changed default values for disable_prompt_cache and disable_speculative_decoding to True.

Update default parameters in endpoint functions
